name: news_flutter
description: A new Flutter application

version: 19.8.0+9

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  #BASE
  cupertino_icons: ^1.0.8
  nb_utils: ^7.0.2
  google_fonts: ^6.2.1
  flutter_vector_icons: ^2.0.0
  intl: ^0.19.0

  #UI
  dots_indicator: ^3.0.0
  cached_network_image: ^3.3.1
  image_picker: ^1.1.0
  shimmer: ^3.0.0
  country_picker: ^2.0.25
  otp_text_field: ^1.1.3

  #FIREBASE
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  firebase_remote_config: ^4.4.2

  #Firebase Notification
  flutter_local_notifications: ^17.1.0
  firebase_messaging: ^14.8.2

  #CONNECTIVITY
  share_plus: ^9.0.0

  http: ^1.2.1
  flutter_custom_tabs: ^2.0.0+1

  # PUSH NOTIFICATION
  onesignal_flutter: ^5.0.4

  # STATE MANAGEMENT
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  # ADS
  google_mobile_ads: ^5.0.0

  # AUTHENTICATION
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1

  #PERMISSION
  permission_handler: ^11.3.1

  #OTHER

  video_player: ^2.8.6
  photo_view: ^0.15.0
  flutter_html: ^3.0.0-beta.2
  flutter_tts: ^4.0.2
  speech_to_text: ^6.6.1
  wakelock_plus: ^1.2.4

  # Color generator
  palette_generator: ^0.3.3+3

  # Location
  geolocator: ^11.0.0

  # Webview
  webview_flutter: ^4.7.0
  url_launcher: ^6.2.6
  flutter_widget_from_html: ^0.14.11
  syncfusion_flutter_pdfviewer: ^25.1.40

  #video players
  appinio_video_player: ^1.2.2
  youtube_player_flutter: ^8.1.2
  # Bottom nav bar
  # persistent_bottom_nav_bar: ^5.0.2
  persistent_bottom_nav_bar:
    git:
      url: https://github.com/HamzaSamirAmmar/PersistentBottomNavBar.git

  lottie: ^3.1.0

  stream_transform: ^2.1.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  syncfusion_flutter_pdfviewer: ^24.2.8

dev_dependencies:
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true

  assets:
    - assets/news/
    - assets/news/flags/
    - assets/news/icons/
    - assets/news/images/
    - assets/news/gif/
