import 'package:nb_utils/nb_utils.dart';

List<LanguageDataModel> getLanguages() {
  return [
    LanguageDataModel(id: 0, name: 'English', languageCode: 'en', flag: 'assets/news/flags/ic_us.png'),
    LanguageDataModel(id: 1, name: 'Hindi', languageCode: 'hi', flag: 'assets/news/flags/ic_india.png'),
    LanguageDataModel(id: 2, name: 'Spanish', languageCode: 'es', flag: 'assets/news/flags/ic_spain.png'),
    LanguageDataModel(id: 3, name: 'Afrikaans', languageCode: 'af', flag: 'assets/news/flags/ic_south_africa.png'),
    LanguageDataModel(id: 4, name: 'French', languageCode: 'fr', flag: 'assets/news/flags/ic_france.png'),
    LanguageDataModel(id: 5, name: 'German', languageCode: 'de', flag: 'assets/news/flags/ic_germany.png'),
    LanguageDataModel(id: 6, name: 'Indonesian', languageCode: 'id', flag: 'assets/news/flags/ic_indonesia.png'),
    LanguageDataModel(id: 7, name: 'Portuguese', languageCode: 'pt', flag: 'assets/news/flags/ic_portugal.png'),
    LanguageDataModel(id: 8, name: 'Turkish', languageCode: 'tr', flag: 'assets/news/flags/ic_turkey.png'),
    LanguageDataModel(id: 9, name: 'Arabic', languageCode: 'ar', flag: 'assets/news/flags/ic_arabic.png'),
    LanguageDataModel(id: 10, name: 'vietnam', languageCode: 'vi', flag: 'assets/news/flags/ic_vitnam.png'),
    LanguageDataModel(id: 11, name: 'Dutch', languageCode: 'nl', flag: 'assets/news/flags/ic_netherlands.png'),
    LanguageDataModel(id: 12, name: 'Gujarati', languageCode: 'gu', flag: 'assets/news/flags/ic_india.png'),
    LanguageDataModel(id: 13, name: 'chinese', languageCode: 'zh', flag: 'assets/news/flags/ic_china.png'),
    LanguageDataModel(id: 14, name: 'japanese', languageCode: 'ja', flag: 'assets/news/flags/ic_japanese.png'),
  ];
}

List<LanguageDataModel> getLanguagesForTTS() {
  return [
    LanguageDataModel(id: 0, name: 'English', languageCode: 'En'),
    LanguageDataModel(id: 1, name: 'Marathi', languageCode: 'IN'),
    LanguageDataModel(id: 2, name: 'Russian', languageCode: 'RU'),
    LanguageDataModel(id: 3, name: 'Chinese', languageCode: 'TW'),
    LanguageDataModel(id: 4, name: 'Hungarian', languageCode: 'HU'),
    LanguageDataModel(id: 5, name: 'Thai', languageCode: 'TH'),
    LanguageDataModel(id: 6, name: 'Urdu', languageCode: ''),
    LanguageDataModel(id: 7, name: 'Norwegian', languageCode: ''),
    LanguageDataModel(id: 8, name: 'Danish', languageCode: 'DK'),
    LanguageDataModel(id: 9, name: 'Turkish', languageCode: 'TR'),
    LanguageDataModel(id: 10, name: 'Estonan', languageCode: 'EE'),
    LanguageDataModel(id: 11, name: 'Bosnian', languageCode: ''),
    LanguageDataModel(id: 12, name: 'Swahili', languageCode: ''),
    LanguageDataModel(id: 13, name: 'Portuguese', languageCode: ''),
    LanguageDataModel(id: 14, name: 'Vietnamese', languageCode: 'VN'),
    LanguageDataModel(id: 15, name: 'Korean', languageCode: 'KR'),
    LanguageDataModel(id: 16, name: 'Swedish', languageCode: 'SE'),
    LanguageDataModel(id: 17, name: 'Arabic', languageCode: ''),
    LanguageDataModel(id: 18, name: 'Sundanese', languageCode: 'ID'),
    LanguageDataModel(id: 19, name: 'Bengali', languageCode: ''),
    LanguageDataModel(id: 20, name: 'Gujarati', languageCode: 'IN'),
    LanguageDataModel(id: 21, name: 'Kannada', languageCode: 'IN'),
    LanguageDataModel(id: 22, name: 'Greek', languageCode: ''),
    LanguageDataModel(id: 23, name: 'Hindi', languageCode: 'IN'),
    LanguageDataModel(id: 24, name: 'Finnish', languageCode: 'FI'),
    LanguageDataModel(id: 25, name: 'Khmer', languageCode: ''),
    LanguageDataModel(id: 26, name: 'Bengali', languageCode: 'IN'),
    LanguageDataModel(id: 27, name: 'French', languageCode: 'FR'),
    LanguageDataModel(id: 28, name: 'Ukrainian', languageCode: 'UA'),
    LanguageDataModel(id: 30, name: 'Dutch', languageCode: 'NL'),
    LanguageDataModel(id: 31, name: 'French', languageCode: 'CA'),
    LanguageDataModel(id: 32, name: 'Serbian', languageCode: ''),
    LanguageDataModel(id: 33, name: 'Portuguese', languageCode: 'BR'),
    LanguageDataModel(id: 34, name: 'Malayalam', languageCode: 'IN'),
    LanguageDataModel(id: 35, name: 'Sinhala', languageCode: ''),
    LanguageDataModel(id: 36, name: 'German', languageCode: 'DE'),
    LanguageDataModel(id: 37, name: 'Kurdish', languageCode: ''),
    LanguageDataModel(id: 38, name: 'Czech', languageCode: ''),
    LanguageDataModel(id: 39, name: 'Polish', languageCode: 'PL'),
    LanguageDataModel(id: 40, name: 'Slovak', languageCode: 'SK'),
    LanguageDataModel(id: 41, name: 'Philippines', languageCode: ''),
    LanguageDataModel(id: 42, name: 'Italian', languageCode: 'IT'),
    LanguageDataModel(id: 43, name: 'Nepali', languageCode: ''),
    LanguageDataModel(id: 44, name: 'Croatian', languageCode: ''),
    LanguageDataModel(id: 46, name: 'Chinese', languageCode: 'CN'),
    LanguageDataModel(id: 47, name: 'Spanish', languageCode: 'ES'),
    LanguageDataModel(id: 48, name: 'Welsh', languageCode: ''),
    LanguageDataModel(id: 49, name: 'Tamil', languageCode: 'IN'),
    LanguageDataModel(id: 50, name: 'Japanese', languageCode: 'JP'),
    LanguageDataModel(id: 51, name: 'Albanian', languageCode: ''),
    LanguageDataModel(id: 52, name: 'Hong Kong', languageCode: 'HK'),
    LanguageDataModel(id: 54, name: 'Spanish', languageCode: 'US'),
    LanguageDataModel(id: 55, name: 'Javanese', languageCode: 'ID'),
    LanguageDataModel(id: 56, name: 'Latin', languageCode: ''),
    LanguageDataModel(id: 57, name: 'Indonesian', languageCode: ''),
    LanguageDataModel(id: 58, name: 'Telugu', languageCode: 'IN'),
    LanguageDataModel(id: 59, name: 'Romanian', languageCode: 'RO'),
    LanguageDataModel(id: 60, name: 'Catalan', languageCode: ''),
  ];
}
